ALTER TABLE api_keys DROP COLUMN IF EXISTS allowed_modules;
DROP TABLE IF EXISTS survey_responses;
DROP TABLE IF EXISTS surveys;
DROP TABLE IF EXISTS experiment_assignments;
DROP TABLE IF EXISTS experiments;
DROP TABLE IF EXISTS alert_rules;
DROP TABLE IF EXISTS email_report_configs;
DROP TABLE IF EXISTS shared_dashboards;
DROP TABLE IF EXISTS session_recordings;
DROP TABLE IF EXISTS click_events;
DROP TABLE IF EXISTS js_errors;
DROP TABLE IF EXISTS outlinks;
DROP TABLE IF EXISTS search_queries;
DROP TABLE IF EXISTS scroll_depths;
DROP TABLE IF EXISTS web_vitals;
DROP TABLE IF EXISTS goal_conversions;
DROP TABLE IF EXISTS goals;
DROP TABLE IF EXISTS funnels;
DROP TABLE IF EXISTS daily_campaigns;
ALTER TABLE events DROP COLUMN IF EXISTS revenue_amount;
ALTER TABLE events DROP COLUMN IF EXISTS revenue_currency;
ALTER TABLE pageviews DROP COLUMN IF EXISTS utm_source;
ALTER TABLE pageviews DROP COLUMN IF EXISTS utm_medium;
ALTER TABLE pageviews DROP COLUMN IF EXISTS utm_campaign;
ALTER TABLE pageviews DROP COLUMN IF EXISTS utm_content;
ALTER TABLE pageviews DROP COLUMN IF EXISTS utm_term;
